#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "dialign.h"
#include "mmstore.h"
int seqnum; char **seq_name; float **glob_sim; char clust_sim[10]; char *upg_str;
float minf2(float a,float b){return a<b?a:b;} float maxf2(float a,float b){return a>b?a:b;}
#include "orig_fn.inc"  /* generated by tree_unit.sh from the ORIGINAL functions.c */
char *upg_orig;
#include "new_fn.inc"
int main(int argc,char**argv){
  int seed=atoi(argv[1]); srand(seed);
  for(int trial=0;trial<400;trial++){
    seqnum=2+rand()%(trial<300?60:250);
    int levels=1+rand()%6;                      /* few distinct values => many ties */
    seq_name=calloc(seqnum,sizeof(char*));
    for(int i=0;i<seqnum;i++){seq_name[i]=malloc(20);sprintf(seq_name[i],"s%-10d",i);}
    glob_sim=(float**)mm_matrix(seqnum,seqnum,sizeof(float));
    for(int i=0;i<seqnum;i++)for(int j=i+1;j<seqnum;j++) glob_sim[i][j]=(float)(rand()%levels)*(rand()%3?1.0f:0.37f);
    const char *m[3]={"av","max","min"};
    strcpy(clust_sim,m[trial%3]);
    av_tree_print_orig(); char *a=upg_str;
    av_tree_print_new();  char *b=upg_str;
    if(strcmp(a,b)){printf("MISMATCH trial %d N=%d mode=%s levels=%d\n",trial,seqnum,clust_sim,levels);return 1;}
  }
  printf("seed %d: 400 random tie-heavy matrices, orig == new\n",seed); return 0;}
